name: ollama-gateway-client

services:
  ollama-gateway-client:
    image: mountainpass/ollama-gateway-client
    container_name: ollama-gateway-client
    ports:
      - "11434:11434"
    environment:
      - TARGET=https://ubuntu:11434
      - APIKEY=nick